version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    # network_mode: "host"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - db-data:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  neo4j:
    # The image to use
    image: neo4j:latest
    # map the ports so we can check the db server is up
    ports:
      - 7474:7474
      - 7687:7687
    # mounting a named volume to the container to track db data
    volumes:
      - neo4j-data:/var/lib/neo4j/data/
      - neo4j-import:/var/lib/neo4j/import/
      - neo4j-plugins:/var/lib/neo4j/plugins/
    env_file:
      - .env.neo4j
  webui:
    build: 
      context: .
      network: host
    ports:
      - 5000:5000
    environment:
      - ENV_NAME='testing'
      - MONGO_DB_NAME='llama-index-dev'
      - MONGO_USERNAME='root'
      - MONGO_PASSWORD='example'
      - MONGO_HOST='mongo:27017'
      - SECRET_KEY='a8ef2798c4e84a0744da509c5da07e30'
      - JWT_SECRET_KEY='ydYdTpdGaF5KnPcPa_UeARTgEIzzpXjemQ8rnZ9ZhFA'
  # worker:
  #   build: ./
  #   entrypoint: celery
  #   command: -A app.celery_tasks.celery_app worker -l info -E
  #   user: nobody
  #   volumes:
  #     - celery-data:/data
  #   environment:
  #     CELERY_BROKER_URL: mongodb://root:example@mongo:27017/llama-index-dev?authSource=admin
  #     CELERY_RESULT_BACKEND: mongodb://root:example@mongo:27017/llama-index-dev?authSource=admin
  #     PYTHONPATH: /data
  #   depends_on:
  #     - mongo
  # flower:
  #   build: ./
  #   command: celery -A app.celery_tasks.celery_app flower
  #   volumes:
  #     - flower-data:/data
  #   working_dir: /data
  #   ports:
  #     - 5555:5555
  #   environment:
  #     CELERY_BROKER_URL: mongodb://root:example@mongo:27017/llama-index-dev?authSource=admin
  #     CELERY_RESULT_BACKEND: mongodb://root:example@mongo:27017/llama-index-dev?authSource=admin
    # depends_on:
    #   - worker
    #   - mongo
volumes:
  db-data: {}
  neo4j-data: {}
  neo4j-plugins: {}
  neo4j-import: {}
  # celery-data: {}
  # flower-data: {}